/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-secondary": "#ffffff",
        outline: "#72787e",
        "primary-fixed": "#cae6ff",
        "surface-container-lowest": "#ffffff",
        "surface-tint": "#376382",
        "tertiary-fixed": "#ffdcc3",
        "on-tertiary-fixed-variant": "#6e3900",
        "secondary-fixed": "#89f5e7",
        "inverse-surface": "#233144",
        "surface-container-low": "#eff4ff",
        "inverse-primary": "#a0ccef",
        "on-secondary-container": "#006f66",
        "on-background": "#0d1c2e",
        "surface-container": "#e6eeff",
        primary: "#003652",
        "on-surface-variant": "#41474d",
        "on-error": "#ffffff",
        "inverse-on-surface": "#eaf1ff",
        "on-primary-fixed": "#001e2f",
        "secondary-fixed-dim": "#6bd8cb",
        "on-primary": "#ffffff",
        "on-tertiary": "#ffffff",
        "on-secondary-fixed-variant": "#005049",
        "surface": "#f8f9ff",
        "on-primary-container": "#92bde0",
        "on-surface": "#0d1c2e",
        "tertiary-container": "#713b00",
        "on-error-container": "#93000a",
        "surface-dim": "#ccdbf3",
        "on-tertiary-fixed": "#2f1500",
        "surface-container-highest": "#d5e3fc",
        secondary: "#006a61",
        "outline-variant": "#c1c7ce",
        error: "#ba1a1a",
        "on-secondary-fixed": "#00201d",
        "error-container": "#ffdad6",
        "surface-container-high": "#dce9ff",
        tertiary: "#502800",
        "primary-fixed-dim": "#a0ccef",
        "tertiary-fixed-dim": "#ffb77d",
        "secondary-container": "#86f2e4",
        background: "#f8f9ff",
        "on-tertiary-container": "#ffa352",
        "on-primary-fixed-variant": "#1b4b69",
        "surface-bright": "#f8f9ff",
        "surface-variant": "#d5e3fc",
        "primary-container": "#1e4d6b",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        full: "9999px",
      },
      spacing: {
        "space-3xl": "4rem",
        "space-xl": "2rem",
        "space-sm": "0.75rem",
        "space-2xs": "0.25rem",
        "container-max": "90rem",
        "gutter-mobile": "1rem",
        "target-min": "3rem",
        "space-xs": "0.5rem",
        "gutter-desktop": "2rem",
        "space-2xl": "3rem",
        "space-lg": "1.5rem",
        "space-md": "1rem",
      },
      maxWidth: {
        "container-max": "90rem",
      },
      fontFamily: {
        sans: [
          "var(--font-noto)",
          "var(--font-noto-latin)",
          "Noto Sans Thai",
          "Noto Sans",
          "sans-serif",
        ],
        display: [
          "var(--font-noto)",
          "var(--font-noto-latin)",
          "Noto Sans Thai",
          "Noto Sans",
          "sans-serif",
        ],
        "label-lg": [
          "var(--font-noto)",
          "var(--font-noto-latin)",
          "Noto Sans Thai",
          "Noto Sans",
          "sans-serif",
        ],
        "body-md": [
          "var(--font-noto)",
          "var(--font-noto-latin)",
          "Noto Sans Thai",
          "Noto Sans",
          "sans-serif",
        ],
        "body-sm": [
          "var(--font-noto)",
          "var(--font-noto-latin)",
          "Noto Sans Thai",
          "Noto Sans",
          "sans-serif",
        ],
        "headline-lg-mobile": [
          "var(--font-noto)",
          "var(--font-noto-latin)",
          "Noto Sans Thai",
          "Noto Sans",
          "sans-serif",
        ],
        "body-lg": [
          "var(--font-noto)",
          "var(--font-noto-latin)",
          "Noto Sans Thai",
          "Noto Sans",
          "sans-serif",
        ],
        "headline-sm": [
          "var(--font-noto)",
          "var(--font-noto-latin)",
          "Noto Sans Thai",
          "Noto Sans",
          "sans-serif",
        ],
        "headline-lg": [
          "var(--font-noto)",
          "var(--font-noto-latin)",
          "Noto Sans Thai",
          "Noto Sans",
          "sans-serif",
        ],
        "headline-md": [
          "var(--font-noto)",
          "var(--font-noto-latin)",
          "Noto Sans Thai",
          "Noto Sans",
          "sans-serif",
        ],
        "title-md": [
          "var(--font-noto)",
          "var(--font-noto-latin)",
          "Noto Sans Thai",
          "Noto Sans",
          "sans-serif",
        ],
        "label-md": [
          "var(--font-noto)",
          "var(--font-noto-latin)",
          "Noto Sans Thai",
          "Noto Sans",
          "sans-serif",
        ],
        "label-sm": [
          "var(--font-noto)",
          "var(--font-noto-latin)",
          "Noto Sans Thai",
          "Noto Sans",
          "sans-serif",
        ],
      },
      fontSize: {
        "label-lg": [
          "18px",
          { lineHeight: "28px", letterSpacing: "0.01em", fontWeight: "600" },
        ],
        "body-md": [
          "16px",
          { lineHeight: "28px", letterSpacing: "0.01em", fontWeight: "400" },
        ],
        "body-sm": [
          "14px",
          { lineHeight: "24px", letterSpacing: "0.015em", fontWeight: "400" },
        ],
        "headline-lg-mobile": [
          "26px",
          { lineHeight: "40px", letterSpacing: "0em", fontWeight: "700" },
        ],
        "body-lg": [
          "18px",
          { lineHeight: "32px", letterSpacing: "0.01em", fontWeight: "400" },
        ],
        "headline-sm": [
          "20px",
          { lineHeight: "32px", letterSpacing: "0.005em", fontWeight: "600" },
        ],
        "headline-lg": [
          "32px",
          { lineHeight: "48px", letterSpacing: "0em", fontWeight: "700" },
        ],
        display: [
          "40px",
          { lineHeight: "60px", letterSpacing: "-0.01em", fontWeight: "700" },
        ],
        "headline-md": [
          "24px",
          { lineHeight: "38px", letterSpacing: "0em", fontWeight: "600" },
        ],
        "title-md": [
          "16px",
          { lineHeight: "24px", fontWeight: "600" },
        ],
        "label-md": [
          "16px",
          { lineHeight: "24px", letterSpacing: "0.01em", fontWeight: "600" },
        ],
        "label-sm": [
          "14px",
          { lineHeight: "20px", letterSpacing: "0.02em", fontWeight: "600" },
        ],
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
